fah = float( input("Fahrenheit Değerinden Hava Sıcaklığını Giriniz: "))
cel = (fah-32)*(5/9)
kel = (cel+273.15)
print("Kelvin Cinsinden Sıcaklık: ",round(kel,2))
print("Celcius Cinsinden Sıcaklık: ",round(cel,2))
